services:
  base-api:
    build: .
    container_name: base-api
    volumes:
      - .:/app
      - ./scripts:/scripts
    stop_signal: SIGTERM
    stop_grace_period: 30s
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_URI=mongodb://base-mongo:27017
      - MONGO_DB=sybilla_db
    ports:
      - "9000:8000"
    depends_on:
      - base-mongo

  base-mongo:
    image: mongo:6
    container_name: base-mongo
    volumes:
      - base_mongo_data:/data/db

  base-mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: base-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=base-mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - base-mongo
    restart: unless-stopped

volumes:
  base_mongo_data: